apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: catalog-service
        version: {{ .Values.catalogservice.deployment.tag }}
    spec:
      containers:
        - name: catalog-service
          image: {{ .Values.catalogservice.deployment.image }}:{{ .Values.catalogservice.deployment.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128M
              cpu: .1
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: catalog-service-config
