apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  annotations:
spec:
  type: LoadBalancer
  selector:
    app: catalog-service
  ports:
    - name: catalog-service-port
      protocol: TCP
      port: 3001
      targetPort: 3001
